<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<div class='ft bank'>
		<div class='ft_title'>
			계좌안내 <span class='english'>BANK ACCOUNT</span>
		</div>
		<div class='ft_body'>
			<div id='ft_bank_mycabin'></div>
			<div id='ft_bank_links'></div>
		</div>
	</div>

</body>
</html>