<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<div class="div">
	<table>
		<tr>
			<td class="align_Center">
				<%@include file="/main/inc/main_bottom1.inc"%>
			</td>
			<td class="align_Center">
				<%@include file="/main/inc/main_bottom2.inc"%>
			</td>
			<td class="align_Center">
				<%@include file="/main/inc/main_bottom3.inc"%>
			</td>
		</tr>
	</table>
	<table>
		<Tr>
			<Td>
				<pre>
				주소 : 전북 전주시 덕진구 여의동 1264-6번지 2F | 사업자등록번호 : 224-26-95516
				통신판매업신고번호 : 2016-전주덕진-0315호 | 개인정보관리자 : 유수인 | 대표 : 김춘겸
				상호명 : 캠핑창고
				전화번호 : 1661-2780 | 팩스번호 : 063-715-4306 | 메일 : master@ccamping.co.kr</pre>
			</Td>
		</Tr>
	</table>
</div>
