<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
<div id='footer_top' align='center'>
		<div class='ft cs'>
			<div class='ft_title'>고객센터 <span class='english'>CUSTOMER CENTER</span></div>
			<div class='ft_body'>
				<div id='ft_qrcode'>
				<!-- <img src="/shop/data/skin/PAPA/img/banner/QRCode_.png" align="absmiddle"> -->
					<a href='/web_project/board/BoardQna.jsp' class='btn_footer_cs'>상품문의</a>
				</div>
				<div id='ft_contact'>
					<div style='margin-bottom:20px;'>
					<span class='ft_business_hours'>
						<b class='ft_bh_head'>상품문의</b>AM 10:00 ~ PM 19:00
					</span>
					<span class='ft_cstel'>031-852-5999</span>
					</div>
					<div>
					<span class='ft_business_hours'>
						<b class='ft_bh_head'>배송문의</b>AM 10:00 ~ PM 19:00
					</span>
					<span class='ft_cstel'>031-852-5999</span>
					</div>
				</div>
				<div id='ft_contact_btn'>
				</div>
			</div>
		</div>

</body>
</html>