<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML>
<HEAD>
<META content="IE=11.0000" http-equiv="X-UA-Compatible">
<META http-equiv="content-type" content="text/html; charset=utf-8">
<META name="description">
<LINK href="/Camp_Project/css/banner_style.css" rel="stylesheet" type="text/css">
<SCRIPT src="/Camp_Project/js/jquery.js" type="text/javascript"></SCRIPT>
<!-- End WOWSlider.com HEAD section -->
<META name="GENERATOR" content="MSHTML 11.00.9600.18639">
</HEAD>
<BODY style="margin: 0px; background-color: rgb(255, 255, 255);">
	<DIV id="wowslider-container1">
		<DIV class="ws_images">
			<UL>
				<LI><IMG id="wows1_0" src="/Camp_Project/image/banner/1.png"></LI>
				<LI><IMG id="wows1_1" src="/Camp_Project/image/banner/2.png"></LI>
				<LI><IMG id="wows1_2" src="/Camp_Project/image/banner/3.png"></LI>
				<LI><IMG id="wows1_3" src="/Camp_Project/image/banner/4.png"></LI>
			</UL>
		</DIV>
		<DIV class="ws_script" style="left: -99%; position: absolute;"></DIV>
		<DIV class="ws_shadow"></DIV>
	</DIV>
	<SCRIPT src="/Camp_Project/js/wowslider.js" type="text/javascript"></SCRIPT>
	<SCRIPT src="/Camp_Project/js/banner_script.js" type="text/javascript"></SCRIPT>
</BODY>
</HTML>
