<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta content="text/html; charset=UTF-8">
<title>Insert title here</title>
</head>
<body>
	<div class='ft notice'>
		<div class='ft_title'>
			<a href='/web_project/notice/boardnoticelist.jsp'>공지사항</a> <span class='english'>NOTICE</span>
		</div>
		<div class='ft_body' style='padding: 10px;'>
			<ul>
				<li><a href='/shop/board/view.php?&id=notice&no=27' style='color: #494949'><span class='date'>16-07-27 7월 무이자 할부 안내 </span></a></li>
				<li><a href='/shop/board/view.php?&id=notice&no=26' style='color: #494949'><span class='date'>16-05-02 5월 무이자 할부 안내</span></a></li>
				<li><a href='/shop/board/view.php?&id=notice&no=25' style='color: #494949'><span class='date'>16-04-01 4월 무이자 할부 안내</span></a></li>
				<li><a href='/shop/board/view.php?&id=notice&no=24' style='color: #494949'><span class='date'>16-03-02 PG사 변경 및 3월 무이자 할부 안내</span></a></li>
				<li><a href='/shop/board/view.php?&id=notice&no=23' style='color: #494949'><span class='date'>16-03-02 페이코(PAYCO) 생에 첫 결제 혜택 이벤트</span></a></li>
				<li><a href='/shop/board/view.php?&id=notice&no=22' style='color: #494949'><span class='date'>16-03-02 사이트 통합 이전 안내</span></a></li>
			</ul>
		</div>
	</div>
	</div>

</body>
</html>